# Generated by Django 2.2 on 2020-03-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dockerhost',
            options={'permissions': (('images_manage', '镜像管理'), ('containers_manage', '容器管理'), ('net_manage', '网络管理')), 'verbose_name': '容器宿主机'},
        ),
    ]
