# Generated by Django 2.2 on 2020-12-30 14:26

import cmdb.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ops.opt


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='关键字段，请谨慎修改', max_length=50, unique=True, verbose_name='主机名/计算机名')),
                ('ip', models.GenericIPAddressField(help_text='若有多个IP且主机名无指定解析则默认为0.0.0.0，请在客户端/etc/hosts中设置其主机名对应IP解析', verbose_name='管理IP')),
                ('protocols', models.CharField(blank=True, default='所有', help_text='主机包含的ssh/rdp/vnc协议/端口json数据, 所有协议则为{"ssh": 22, "vnc": 5901, "rdp": 3389}', max_length=150, verbose_name='协议类型')),
                ('name', models.CharField(blank=True, default='', help_text='备注标签, 便于人员识别', max_length=100, null=True, verbose_name='标识名称')),
                ('other_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='其它IP')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, '在用'), (2, '备用'), (3, '故障'), (4, '下线'), (6, '其它')], default=1, null=True, verbose_name='设备状态')),
                ('asset_type', models.SmallIntegerField(blank=True, choices=[(1, '物理机'), (2, '虚拟机'), (3, '容器'), (4, 'H3C交换机'), (6, '其它')], default=2, null=True, verbose_name='设备类型')),
                ('os', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='操作系统')),
                ('cpu_model', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='CPU型号')),
                ('cpu_num', models.CharField(blank=True, default='', help_text='物理核个数, 逻辑核个数(intel超线程)', max_length=100, null=True, verbose_name='CPU数量')),
                ('memory', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='内存大小')),
                ('disk', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='硬盘信息')),
                ('vendor', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='供应商')),
                ('sn', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='主机序列号')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('changetime', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('buydate', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='购买日期')),
                ('position', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='所处位置')),
                ('sernumb', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='服务编号')),
                ('sercode', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='服务代码')),
                ('kernel', models.CharField(blank=True, default='', max_length=60, verbose_name='系统内核版本')),
                ('enable', models.BooleanField(default=True, verbose_name='启用')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '主机',
                'ordering': ['group', 'ip'],
                'permissions': (('ssh_host', '主机远程控制'), ('sftp_host', '网页sftp')),
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='组名/区域')),
                ('ip', models.CharField(blank=True, default='', help_text='IP开头字符，比如Core组IP为10.2.4.开头。用于客户端脚本添加新主机时自动设置组，不支持通配符', max_length=20, verbose_name='IP匹配')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '主机分组',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='标识名称，当不同服务器使用相同的SSH账号名，但密码不同时，此项名称可进行区分。', max_length=50, verbose_name='名称')),
                ('protocol', models.CharField(choices=[('ssh', 'ssh'), ('rdp', 'rdp'), ('vnc', 'vnc')], default='ssh', max_length=8, verbose_name='协议类型')),
                ('username', models.CharField(blank=True, default='', help_text='VNC协议时用户名忽略, 填任意', max_length=50, verbose_name='用户名')),
                ('password', ops.opt.EncryptField(blank=True, default='', max_length=150, verbose_name='密码')),
                ('rsa_key', models.TextField(blank=True, default='', help_text='SSH协议类型使用密钥登录时输入RSA私钥，如果密码方式登陆，则留空', null=True, verbose_name='SSH私钥')),
                ('auto', models.BooleanField(default=False, help_text='开启自动，且RSA私钥为空时，crontab将每天定时修改密码', verbose_name='自动修改密码')),
                ('autotime', models.DateTimeField(auto_now=True, help_text='最近一次自动修改密码时间', null=True, verbose_name='最近改密')),
                ('changetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改')),
                ('enable', models.BooleanField(default=True, verbose_name='启用')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '主机用户',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='主机')),
                ('host_user', models.CharField(blank=True, default='', help_text='VNC协议时为空, 无用户', max_length=255, null=True, verbose_name='主机账号')),
                ('http_user', models.CharField(max_length=50, verbose_name='网站用户')),
                ('type', models.SmallIntegerField(blank=True, choices=[(1, 'WebSSH'), (2, 'Xshell'), (3, 'SecureCRT'), (8, 'RDP'), (9, 'VNC')], default=1, null=True, verbose_name='终端类型')),
                ('log', models.CharField(default=cmdb.models.get_logname, editable=False, max_length=100, unique=True, verbose_name='文件名')),
                ('cmds', models.TextField(blank=True, default='', help_text='用户终端操作所执行的命令记录', null=True, verbose_name='命令记录')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '终端操作记录',
                'ordering': ['-start_time'],
                'permissions': (('kill_session', '强制结束终端'), ('play_session', '播放操作录像'), ('monitor_session', '监视操作')),
            },
        ),
        migrations.CreateModel(
            name='Perm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='名称')),
                ('enable', models.BooleanField(default=True, verbose_name='启用')),
                ('changetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('host', models.ManyToManyField(blank=True, to='cmdb.Host', verbose_name='主机')),
                ('host_user', models.ManyToManyField(blank=True, to='cmdb.HostUser', verbose_name='主机用户')),
                ('hostgroup', models.ManyToManyField(blank=True, to='cmdb.HostGroup', verbose_name='机组')),
                ('web_user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='网站用户')),
                ('web_usergroup', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='网站用户组')),
            ],
            options={
                'verbose_name': '用户主机授权',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='group',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.HostGroup', verbose_name='机组'),
        ),
    ]
